spring:
  application:
    name: ACMParcelDev
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://db:5432/shipping_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true